# $NetBSD: npfl2test.conf,v 1.13 2025/06/01 00:48:41 joe Exp $

$ext_if = "npftest0"
$int_if = "npftest1"

#
# RFC 7042
#
# 00:00:5E:00:53:00 - 00:00:5E:00:53:FF
$mac1 = 00:00:5E:00:53:00
$mac2 = 00:00:5E:00:53:01
$mac3 = 00:00:5E:00:53:02
$nested_mac4 = { 00:00:5E:00:53:03, 00:00:5E:00:53:04, 00:00:5E:00:53:05 }

group "ext2" on $int_if layer-2 {
	ruleset "l2-ruleset" layer-2
	pass ether in final from $mac1 to $mac2 type Ex86DD
	block ether in final from $mac2
	pass ether out final to $mac3 type Ex809B
	pass ether in final from $nested_mac4
}

group default layer-2 {
	block ether all
}